name: pages
on:
  push:
    branches:
      - main
      - pages

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: ü§ò checkout
        uses: actions/checkout@v2

      - name: ‚öô jekyll
        run: |
          sudo gem install bundler
          bundle install

      - name: üñâ repo
        run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: üôè build
        run: bundle exec jekyll build -b ${{ env.REPOSITORY }}
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ‚úì commit
        run: |
          cd _site
          git init
          git add -A
          git config --local user.email "hello@clarius.org"
          git config --local user.name "GitHub Action"
          git commit -m "Publish pages from ${GITHUB_REPOSITORY}@${GITHUB_SHA:0:9}"

      - name: üöÄ push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.CLARIUS_ACCESS_TOKEN }}
          repository: clarius/${{ env.REPOSITORY }}
          branch: gh-pages
          force: true
          directory: ./_site